---
- name: set jenkins up
  hosts: all
  become: yes
  vars:
    jenkins_repo: /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
    jenkins_key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  tasks:
    - name: install openjdk8
      yum:
        name: java-1.8.0-openjdk
        state: latest

    - name: add jenkins repo
      shell: wget -O {{ jenkins_repo  }}
    
    - name: import the key
      shell: rpm --import {{ jenkins_key }}

    - name: upgrade packages
      yum:
        name: '*'
        state: latest

    - name: install jenkins
      yum:
        name: 'jenkins'
        state: latest
  
    - name: enable jenkins
      service:
        name: jenkins
        state: started
        enabled: yes

